### ISSUE TITLE
moving from circleCI 1.0 to 2.0

### ISSUE THREAD

**Issue by djarecka** [ReproNim/regtests#2]

**Comment by djarecka** [comment]
@kaczmarj : great!

**Comment by djarecka** [comment]
we should remove `pip install https://github.com/kaczmarj/neurodocker/archive/master.tar.gz`, since we decided to use neurodocker container

**Comment by djarecka** [comment]
I wonder if we shouldn't use retry in CircleCI when building the image. Today I had to try at least 5 times before I succeeded

**Comment by kaczmarj** [comment]
@djarecka - what was the error that you had to retry multiple times?

**Comment by djarecka** [comment]
@kaczmarj - every time different, looked to me like issues with the connection
